#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)
alias manager="sh ${here}/manager"


# Check number of arguments.
if [ $# -eq 0 ]; then
    echo "E: The ${name} command takes at least one argument"
    exit 1
fi

# Parse arguments.
repo_install=0
while [ $# -gt 0 ]; do
    case "$1" in
        openssl-1.0.2)
            sh ${here}/manager-install-openssl 1.0.2j
        ;;
        openssl-1.1.1)
            sh ${here}/manager-install-openssl 1.1.1k
        ;;
        pyenv)
            sh ${here}/manager-install-$1
        ;;
        python-pip|python-setuptools|python-wheel)
            sh ${here}/manager-install-$1
        ;;
        python-cython|python-numpy|python-scipy)
            sh ${here}/manager-install-$1
        ;;
        python-2.*|python-3.*)
            sh ${here}/manager-install-python "$(echo $1 | cut -d- -f2)"
        ;;
        *)
            case "$1" in
                gcc-full|pkg-config|blas|lapack|matplotlib-dev|pyenv-dev)
                    pkglist="$(manager info $1)"
                ;;
                hdf4|hdf5|netcdf4)
                    if [ "$(manager info os-name)" = "centos" ]; then
                        manager install epel-release
                    fi
                    pkglist="$(manager info $1)"
                ;;
                *)
                    pkglist="$1"
                ;;
            esac
            pkgman=$(manager info os-package-manager)
            case ${pkgman} in
                apt-get)
                    aptversion=$(apt-get --version | head -n1 | cut -d' ' -f2)
                    case "${aptversion}" in
                        0.[0-6].*)
                            norecommends=
                        ;;
                        *)
                            norecommends=--no-install-recommends
                        ;;
                    esac
                ;;
                zypper)
                    norecommends=--no-recommends
                ;;
                *)
                    norecommends=
                ;;
            esac
            if [ ${repo_install} -eq 0 ]; then
                manager update
                repo_install=1
            fi
            # Create some dummy locale folders.
            for item in $(echo "af ar be bg bs ca cs cy da de dz el           \
                                en@boldquot en@quot en_GB eo es et eu         \
                                fi fr ga gl he hr hu id it ja km ko ku        \
                                ky lg lt mr ms nb ne nl nn no pa pl pt        \
                                pt_BR ro ru rw sk sl sr sv th tl tr uk        \
                                vi zh_CN zh_TW"); do
                mkdir -p /usr/share/locale/${item}/LC_MESSAGES
                mkdir -p /usr/share/locale/${item}/LC_TIME
            done
            # Create some dummy man folders.
            for item in $(echo "de es fr hu ja man1 man3 man5 man7 man8       \
                                pl pt_BR ru sv"); do
                mkdir -p /usr/share/man/${item}
            done
            # Finally call the install command.
            ${pkgman} install -y ${norecommends} ${pkglist}
        ;;
    esac
    shift
done

if [ ${repo_install} -eq 1 ]; then
    manager clean
fi
