#! /bin/sh

set -e
here=$(readlink -f "$0" | xargs dirname)
name=$(readlink -f "$0" | xargs basename)
alias manager="sh ${here}/manager"


_info_os_arch() {
    case "$(_info_os_name)" in
        debian|ubuntu)
            echo $(dpkg --print-architecture)
        ;;
        centos|opensuse*|sles)
            if [ -f /lib64/libc.so.6 ]; then
                echo "amd64"
            elif [ -f /lib/libc.so.6 ]; then
                echo "i386"
            else
                echo ""
            fi
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_os_name() {
    if [ -f /etc/os-release ]; then
        echo $(grep ^ID= /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
    elif [ -f /etc/debian_version ]; then
        echo "debian"
    else
        echo "E: Unknown operating system"
        exit 1
    fi
}


_info_os_version() {
    if [ -f /etc/os-release ]; then
        echo $(grep ^VERSION_ID /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
    elif [ -f /etc/debian_version ]; then
        echo $(cat /etc/debian_version)
    else
        echo "E: Unknown operating system version"
        exit 1
    fi
}


_info_os_version() {
    if [ -f /etc/os-release ]; then
        echo $(grep ^VERSION_ID /etc/os-release | cut -d= -f 2 | sed -r 's/^"|"$//g')
    elif [ -f /etc/debian_version ]; then
        echo $(cat /etc/debian_version)
    else
        echo "E: Unknown operating system version"
        exit 1
    fi
}


_info_os_package_manager() {
    case "$(_info_os_name)" in
        debian|ubuntu)
            echo "apt-get"
        ;;
        centos)
            echo "yum"
        ;;
        opensuse*|sles)
            echo "zypper"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)'"
            exit 1
        ;;
    esac
}


_info_hdf4() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-[45].0*)
            echo "libhdf4g libhdf4g-dev"
        ;;
        ubuntu-*)
            echo "libhdf4-0 libhdf4-dev"
        ;;
        centos-*)
            echo "hdf hdf-devel"
        ;;
        opensuse*-*|sles-*)
            echo "libhdf4 hdf-devel hdf-devel-static"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_hdf5() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-4.0*)
            echo "libhdf5-serial-1.6.5-0 libhdf5-serial-dev"
        ;;
        debian-5.0*)
            echo "libhdf5-serial-1.6.6-0 libhdf5-serial-dev"
        ;;
        ubuntu-*)
            echo "libhdf5-103 libhdf5-dev"
        ;;
        centos-*)
            echo "hdf5 hdf5-devel hdf5-static"
        ;;
        opensuse*-*|sles-*)
            echo "libhdf5 hdf5-devel hdf5-devel-static"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_blas() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-4.0*)
            echo "refblas3 refblas3-dev"
        ;;
        debian-5.0*)
            echo "libblas3gf libblas-dev"
        ;;
        ubuntu-*)
            echo "libblas3 libblas-dev"
        ;;
        centos-*)
            echo "blas blas-devel blas-static"
        ;;
        opensuse*-*|sles-*)
            echo "libblas3 blas-devel blas-devel-static"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_lapack() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-4.0*)
            echo "lapack3 lapack3-dev"
        ;;
        debian-5.0*)
            echo "liblapack3gf liblapack-dev"
        ;;
        ubuntu-*)
            echo "liblapack3 liblapack-dev"
        ;;
        centos-*)
            echo "lapack lapack-devel lapack-static"
        ;;
        opensuse*-*|sles-*)
            echo "liblapack3 lapack-devel lapack-devel-static"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_netcdf4() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-5.0*)
            echo "libnetcdf4 libnetcdf-dev"
        ;;
        ubuntu-*)
            echo "libnetcdf15 libnetcdf-dev"
        ;;
        centos-*)
            echo "netcdf netcdf-devel netcdf-static"
        ;;
        opensuse*-*|sles-*)
            echo "libnetcdf18 netcdf-devel netcdf-devel-static"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_matplotlib_dev() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-[45].0*)
            echo "libfreetype6-dev libpng12-dev"
        ;;
        ubuntu-*)
            echo "libfreetype-dev libpng-dev"
        ;;
        centos-*)
            echo "freetype-devel libpng-devel"
        ;;
        opensuse*-*|sles-*)
            echo "freetype-devel libpng16-devel"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_openssl_root() {
    version=1.1.1k
    if [ ! -z "$1" ]; then
        version="$1"
    fi
    regex="1\.(0\.2[a-u]?|1\.1[a-k]?)"
    if [ -z $(echo "${version}" | grep -E "^${regex}$" || true) ]; then
        echo "E: Invalid openssl version '$1'"
        exit 1
    fi
    version_short=$(echo ${version} | sed -r 's|(([0-9]\.)+[0-9])[a-z]?|\1|g')
    echo /opt/openssl-${version_short}
}


_info_gcc_full() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-[45].0*|ubuntu-*)
            echo "gcc g++ gfortran"
        ;;
        centos-*)
            echo "gcc gcc-c++ gcc-gfortran"
        ;;
        opensuse*-*|sles-*)
            echo "gcc gcc-c++ gcc-fortran"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_pkg_config() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-[45].0*|ubuntu-*|opensuse*-*|sles-*)
            echo "pkg-config"
        ;;
        centos-*)
            echo "pkgconfig"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_libffi() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-4.0*)
            echo "libffi4"
        ;;
        debian-[56].0*)
            echo "libffi5"
        ;;
        ubuntu-8.04*)
            echo "libffi4"
        ;;
        ubuntu-8.10*|ubuntu-9.*|ubuntu-10.*|ubuntu-11.04*)
            echo "libffi5"
        ;;
        ubuntu-11.10*|ubuntu-1[2-9].*)
            echo "libffi6"
        ;;
        ubuntu-2[01].*)
            echo "libffi7"
        ;;
        centos-*)
            echo "libffi"
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_pyenv_dev() {
    case "$(_info_os_name)-$(_info_os_version)" in
        debian-4.0*)
            echo "
                build-essential libncursesw5-dev libreadline-dev              \
                libsqlite3-dev libffi-dev zlib1g-dev libbz2-dev               \
            " | xargs
        ;;
        debian-5.0*|ubuntu-*)
            echo "
                build-essential tk-dev libncursesw5-dev libreadline-dev       \
                libsqlite3-dev libffi-dev xz-utils zlib1g-dev libbz2-dev      \
                liblzma-dev                                                   \
            " | xargs
        ;;
        centos-*)
            echo "
                @development findutils llvm readline-devel sqlite-devel       \
                libffi-devel xz-devel bzip2-devel zlib-devel                  \
            " | xargs
        ;;
        opensuse*-*|sles-*)
            echo "
                automake tk-devel ncurses-devel readline-devel                \
                sqlite3-devel libffi-devel xz-devel libbz2-devel zlib-devel
            " | xargs
        ;;
        *)
            echo "E: Unknown operating system '$(_info_os_name)-$(_info_os_version)'"
            exit 1
        ;;
    esac
}


_info_pyenv_profile() {
    echo /etc/profile.d/01-pyenv-init.sh
}


_info_pyenv_root() {
    echo /opt/pyenv
}


_info_profile() {

    echo \
'# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "`id -u`" -eq 0 ]; then
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
    PATH="/usr/local/bin:/usr/bin:/bin"
fi

if [ "$PS1" ]; then
    if [ "$BASH" ]; then
        PS1='"'"'\u@\h:\w\$ '"'"'
    elif [ "`id -u`" -eq 0 ]; then
        PS1="[root@$HOSTNAME]# "
    else
        PS1="[$USER@$HOSTNAME]$ "
    fi
fi

if [ -d /etc/profile.d ]; then
    for i in /etc/profile.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    done
    unset i
fi
'

}


case "$1" in
    blas|lapack|hdf4|hdf5|netcdf4|matplotlib-dev)
        _info_$(echo $1 | tr - _)
    ;;
    gcc-full|pkg-config|libffi)
        _info_$(echo $1 | tr - _)
    ;;
    openssl-root)
        shift
        _info_openssl_root $@
    ;;
    os-arch|os-name|os-version|os-package-manager|profile)
        _info_$(echo $1 | tr - _)
    ;;
    pyenv-dev|pyenv-profile|pyenv-root)
        _info_$(echo $1 | tr - _)
    ;;
    *)
        echo "E: Unknown option '$1'"
        exit 1
    ;;
esac
